### ISSUE TITLE
I Just Want to say...

### ISSUE THREAD

**Issue by EclipseKnight** [David-vz/MonsterHunterPortable3rdHDRemake#2]
I'm so glad to see this old game get another remake of textures. I currently play via a huge server of hunters (if you want a link to the site just ask). I'm here to let you know if you need any help in game wise then I can offer some service. In terms of making textures likely not. Not really my specialty. Whatever errors I find in game, or comparisons you need I can definitely help out.  If there is some way you want to get in touch with me Just ask. Not to sure if I should place me email here for privacy reasons.

**Comment by David-vz** [comment]
Thanks Eclipse. I know we spoke on Discord way back.
Send me a message to myself or ice-wind if you still get time and want to help out. 
Ice-wind has been super active and I myself have been too busy the last while to really get to anything.
