### ISSUE TITLE
hello i like to work on this peoject update something i can like some map and etc. 

### ISSUE THREAD

**Issue by po456asd** [David-vz/MonsterHunterPortable3rdHDRemake#3]
but i can't find base texture anywhere. any idea? i want to insert new sprite but i don't know where i should save file to and what it old name.

**Comment by po456asd** [comment]
ok i know how it work. now but another question can i have wiiu texture that already extract from you?

**Comment by David-vz** [comment]
Hey po456asd.

Thanks for the contributions to the project!
Sorry had a busy time and haven't been giving this the attention it deserves.

If you're still interested let me know and i'll walk you through how I've done the maps and help you with the wii and wii u textures workflow

**Comment by Ice-w1nd** [comment]
Omg you are alive David! I sent you a private message on reddit a few weeks ago, and since then i've been working on some textures for p3rd (I'm the main guy behind the mhfu retexture project). I still need to fully understand how github works though.

**Comment by po456asd** [comment]
i still interest and want to work on this project while i'm free from collage project. 
first off. compare our repo what is newer i don't really know what you pull is newest or older one.
second. i want that wiiu texture to replace the one in mh3rd. but i can't find how to extract texture from it.

**Comment by David-vz** [comment]
po456asd, just wanted to make sure I follow up on any open tickets.
Ice-w1nd is currently the driving force on this project and I'm out of commission for the time being.
Send him a DM if there are anything you still want to help with.
